import { AssessmentTest, Questions, User } from "./types";
const tomorrow = new Date(Date.now() + 1000 * 60 * 60 * 24);
const yesterday = new Date(Date.now() - 1000 * 60 * 60 * 24);

export const mockLoginUsers: User[] = [
  {
    id: "admin-1",
    name: "Admin Lead",
    email: "admin@example.com",
    role: "admin",
  },
  {
    id: "participant-1",
    name: "Priya Sharma",
    email: "priya@example.com",
    role: "participant",
    password: "123123",
  },
  {
    id: "participant-2",
    name: "Rahul Singh",
    email: "rahul@testing.com",
    role: "participant",
    password: "123123",
  },
  {
    id: "participant-3",
    name: "Test User",
    email: "test@user.com",
    role: "participant",
    password: "123123",
  },
];

export const seedQuestions: Questions[] = [
  {
    id: "q-001",
    question: "Which HTML element defines the main content of a document?",
    optionA: "section",
    optionB: "main",
    optionC: "article",
    optionD: "body",
    correct: "B",
    category: "HTML",
    difficulty: "Easy",
  },
  {
    id: "q-002",
    question: "Which CSS property controls the space between grid columns?",
    optionA: "column-gap",
    optionB: "grid-space",
    optionC: "column-space",
    optionD: "grid-padding",
    correct: "A",
    category: "CSS",
    difficulty: "Easy",
  },
  {
    id: "q-003",
    question: "What does React use to keep UI in sync with state changes?",
    optionA: "A template compiler",
    optionB: "A virtual DOM and reconciliation",
    optionC: "Server polling",
    optionD: "Manual DOM selectors",
    correct: "B",
    category: "React",
    difficulty: "Medium",
  },
  {
    id: "q-004",
    question: "Which TypeScript feature narrows a value after a runtime check?",
    optionA: "Type guards",
    optionB: "Namespaces",
    optionC: "Decorators",
    optionD: "Declaration merging",
    correct: "A",
    category: "TypeScript",
    difficulty: "Medium",
  },
  {
    id: "q-005",
    question: "Which HTTP status code means unauthorized?",
    optionA: "400",
    optionB: "401",
    optionC: "403",
    optionD: "409",
    correct: "B",
    category: "Web",
    difficulty: "Easy",
  },
  {
    id: "q-006",
    question:
      "Which browser API is best for moving CSV parsing off the UI thread?",
    optionA: "Web Worker",
    optionB: "Intersection Observer",
    optionC: "Resize Observer",
    optionD: "Clipboard API",
    correct: "A",
    category: "Performance",
    difficulty: "Easy",
  },
  {
    id: "q-007",
    question:
      "What should a route guard verify before rendering protected content?",
    optionA: "Only the URL path",
    optionB: "Session validity and role",
    optionC: "Screen width",
    optionD: "Browser language",
    correct: "B",
    category: "Security",
    difficulty: "Medium",
  },
  {
    id: "q-008",
    question:
      "Which ARIA technique announces changing timer text to assistive tech?",
    optionA: "aria-hidden",
    optionB: "aria-current",
    optionC: "aria-live",
    optionD: "aria-pressed",
    correct: "C",
    category: "Accessibility",
    difficulty: "Easy",
  },
  {
    id: "q-009",
    question: "What is the purpose of React.lazy?",
    optionA: "Route or component code splitting",
    optionB: "Encrypting JavaScript",
    optionC: "CSS minification",
    optionD: "Disabling hydration",
    correct: "A",
    category: "Performance",
    difficulty: "Medium",
  },
  {
    id: "q-010",
    question: "Which meta tags are useful when sharing a result page?",
    optionA: "Open Graph tags",
    optionB: "Viewport only",
    optionC: "Charset only",
    optionD: "Refresh tags",
    correct: "A",
    category: "SEO",
    difficulty: "Medium",
  },
];

export const seedTests: AssessmentTest[] = [
  {
    id: "test-frontend-core",
    title: "Frontend Core Skills",
    questionIds: seedQuestions.slice(0, 8).map((question) => question.id),
    timeLimitMinutes: 12,
    passPercentage: 60,
    createdAt: new Date().toISOString(),
    expiresAt: tomorrow.toISOString(),
  },
  {
    id: "test-platform-readiness",
    title: "Platform Readiness Check",
    questionIds: seedQuestions.slice(4, 10).map((question) => question.id),
    timeLimitMinutes: 8,
    passPercentage: 70,
    createdAt: yesterday.toISOString(),
    expiresAt: yesterday.toISOString(),
  },
];
